version: '3'

services:
  poc-micronaut:
    image: poc_micronaut_service:1.0
    ports:
      - "80:80"
    environment:
      - JWT_GENERATOR_SIGNATURE_SECRET=BB36D3765316D495DCDCC5B86DF45
      - AWS_KEY_ID=id
      - AWS_SECRET_KEY=secret-key
      - AWS_SESSION_TOKEN=token
      - AWS_REGION=eu-west-1
      - AWS_ENDPOINT=http://localstack:8000

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=dynamodb
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=id
      - AWS_SECRET_ACCESS_KEY=secret-key
      - USE_SSL=0
    ports:
    - "4566:4566"
    - "8089:8080"
    volumes:
      #manter os dados salvos
      -  ./tmp:/tmp/localstack
      #pasta onde script ficam e são inicializados em ordem alfabética
      - ./mock:/docker-entrypoint-initaws.d

  localstack-setup:
    build:
      context: .
      dockerfile: Dockerfile.localstack
    image: localstack-setup
    depends_on:
      - localstack