FROM amazon/aws-cli:latest as base

RUN mkdir -p /table

#copiar arquivo para essa pasta
COPY client-table.json /table/

WORKDIR /table

#CMD ["aws dynamodb list-tables"]

#cadastrar credenciais na pasta correta da aws
CMD ["aws dynamodb create-table --table-name DbClient --attribute-definitions AttributeName=clientId,AttributeType=S --key-schema AttributeName=clientId,KeyType=HASH --provisioned-throughput ReadCapacityUnits=10,WriteCapacityUnits=10 --endpoint-url http://localhost:4566"]



