FROM amazon/aws-cli:latest as aws-cli

WORKDIR /setup

COPY --chown=root:root ./localstack/aws/configuration /root/.aws/config
COPY --chown=root:root ./localstack/aws/credentials /root/.aws/credentials
COPY --chown=root:root ./localstack/create-resources.sh .
COPY --chown=root:root ./localstack/files .

RUN chmod +x create-resources.sh

CMD ["setup/create-resource.sh"]