### micronaut ###
micronaut:
  application:
    name: poc
  server:
    port: 80
  security:
    authentication: bearer
  token:
    jwt:
      signatures:
        secret:
          generator:
            secret: "${JWT_GENERATOR_SIGNATURE_SECRET:BB36D3765316D495DCDCC5B86DF45}"
            base64: true
            access-token:
              expiration: 60

### aws ###
aws:
  accessKeyId: "id"
  secretKey: "secret-key"
  sessionToken: "token"
  region: "eu-west-1"
  endpoint: "http://localhost:8000"
